/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "Eos_5tonne"
/rat/db/set DETECTOR geo_file "Eos_5tonne/Eos_5tonne.geo"
/rat/db/set GEO[pmts] pos_table "PMTINFO_40pct_coverage"

/run/initialize
/tracking/storeTrajectory 1

/rat/proc splitevdaq

/rat/proc count
/rat/procset update 1

/rat/proclast outroot

/generator/add combo gun2:point
/generator/vtx/set e- 0 0 0 0 10.0 10.0
/generator/pos/set 0 0 0

/run/beamOn 10
