/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "Validation"
/rat/db/set DETECTOR geo_file "Validation/Valid.geo"

/run/initialize

/rat/proc splitevdaq
/rat/proc count
/rat/procset update 100

/rat/proc classifychargebalance

/rat/proclast outroot

/generator/add combo gun:point:poisson
/generator/vtx/set e- 0.0 0.0 0.0 2.5
/generator/pos/set 0.0 0.0 0.0

/run/beamOn 100
