/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

#/rat/db/set DETECTOR experiment "Watchman"
#/rat/db/set GEO[inner_pmts] mu_metal 1
#/rat/db/set DETECTOR detector_factory "Watchman"
#/rat/db/set WATCHMAN_PARAMS photocathode_coverage 0.25

/rat/db/set DETECTOR experiment "Watchman"
/rat/db/set DETECTOR detector_factory "Watchman"
/rat/db/set WATCHMAN_PARAMS photocathode_coverage 0.20
/rat/db/set WATCHMAN_PARAMS veto_coverage 0.02 
/rat/db/set GEO[tank] r_max 11026.350000
/rat/db/set GEO[detector] r_max 10024.762500
/rat/db/set GEO[shield] detector_size_d 20052.700000
/rat/db/set GEO[tank] size_z 11026.350000
/rat/db/set GEO[shield] detector_size_z 20052.700000
/rat/db/set GEO[detector] size_z 10024.762500

#/rat/db/set GEO[cables] size_z 10024.762500
/rat/db/set GEO[shield] veto_thickness_r 1500.000000
/rat/db/set GEO[shield] veto_thickness_z 5000.000000
/rat/db/set GEO[shield] steel_thickness 6.350000




# Visualize the calibration source
#/rat/db/load Watchman/DecayChamber.geo
#/rat/db/set GEO[sourcecan] posz 10000.0

/run/initialize

/vis/open OGLSQt
/vis/scene/create
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/viewer/set/upVector 0.0 0.0 1.0
/vis/viewer/set/viewpointThetaPhi -90 135 
/vis/viewer/set/style s
/vis/viewer/flush

## Cut a plane through the detector
/vis/viewer/addCutawayPlane 0 0 0 cm 1 0 0
#/vis/viewer/addCutawayPlane 0 -100 0 cm 0 1 0
#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/zoomTo 10
#/vis/viewer/panTo 10 0
