/glg4debug/glg4param omit_muon_processes 1.0
/glg4debug/glg4param omit_hadronic_processes 1.0

/rat/db/set DETECTOR experiment "Validation"
/rat/db/set DETECTOR geo_file "Validation/Valid.geo"


/rat/db/set LED[default] intensity 1000

# Multiple LEDs are cycled through in order
/rat/db/set LED[default] x [2000,2000,2000,2000,2000]
/rat/db/set LED[default] y [0,0,0,0,0]
/rat/db/set LED[default] z [-2000,-1000,0,1000,2000]

/rat/db/set LED[default] angle_mode "dist"
/rat/db/set LED[default] dist_angle [0.0,0.05]

# Where to shoot the leds
# Option 1: Aim at targets
/rat/db/set LED[default] fire_at_target true
/rat/db/set LED[default] target_x [0,0,0,0,0]
/rat/db/set LED[default] target_y [0,0,0,0,0]
/rat/db/set LED[default] target_z [0,0,0,0,0]
# Option 2: Fire along a given direction vector
/rat/db/set LED[default] fire_at_target false
/rat/db/set LED[default] dir_x [-1,-1,-1,-1,-1]
/rat/db/set LED[default] dir_y [0,0,0,0,0]
/rat/db/set LED[default] dir_z [0,0,0,0,0]

# Wavelength options
/rat/db/set LED[default] wl_mode "dist"
/rat/db/set LED[default] dist_wl [390,400,410]
/rat/db/set LED[default] dist_wl_intensity [0.5,1,0.5]


/run/initialize

/vis/open OGLSQt
/vis/scene/create
/vis/scene/add/trajectories rich smooth
/tracking/storeTrajectory 1
/tracking/FillPointCont 1
/vis/scene/add/volume
/vis/sceneHandler/attach
/vis/viewer/set/upVector 0.0 0.0 1.0
/vis/viewer/set/viewpointThetaPhi -90 135 
/vis/viewer/set/style s
#/vis/viewer/flush
/vis/scene/endOfEventAction accumulate

## Cut a plane through the detector
/vis/viewer/addCutawayPlane -100.0 0 0 cm 1 0 0
#/vis/viewer/addCutawayPlane 0 -100 0 cm 0 1 0
#/vis/viewer/set/viewpointThetaPhi -90 0
#/vis/viewer/zoomTo 10
#/vis/viewer/panTo 10 0

/generator/add led default

/run/beamOn 10
