# Helpers for assembling the single RAT ROOT dictionary (RATDict) from headers
# contributed by multiple source subdirectories.
#
# Each module calls:
#   * rat_dictionary_headers() with the headers (named as they are #included,
#     e.g. RAT/DS/Root.hh) it wants reflected into the dictionary, and
#   * rat_dictionary_linkdef() with its LinkDef fragment (also named as it is
#     #included, e.g. RAT/DS/LinkDef.hh).
#
# Both accumulate in GLOBAL properties. After every subdirectory is processed,
# src/CMakeLists.txt calls rat_generate_linkdef() to emit a global LinkDef that
# #includes each fragment, and feeds the collected headers + that LinkDef to
# root_generate_dictionary() once. Order of registration does not matter, and
# fragments are resolved on rootcling's include path (RATPAC_INCLUDE_DIR).

# Register one or more headers for inclusion in the RAT ROOT dictionary.
function(rat_dictionary_headers)
  set_property(GLOBAL APPEND PROPERTY RATDICT_HEADERS ${ARGN})
endfunction()

# Register one or more LinkDef fragments for the global RAT dictionary LinkDef.
function(rat_dictionary_linkdef)
  set_property(GLOBAL APPEND PROPERTY RATDICT_LINKDEFS ${ARGN})
endfunction()

# Generate the global LinkDef that #includes every registered fragment, writing
# it to ${output_path} and returning that path in ${out_var}.
function(rat_generate_linkdef out_var output_path)
  get_filename_component(abs_output "${output_path}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_BINARY_DIR}")
  get_property(fragments GLOBAL PROPERTY RATDICT_LINKDEFS)
  set(content "// Auto-generated by rat_generate_linkdef(); do not edit.\n")
  string(APPEND content "// Global LinkDef for the RAT ROOT dictionary (RATDict).\n")
  string(APPEND content "// Each entry is a per-module fragment registered via rat_dictionary_linkdef().\n")
  foreach(fragment ${fragments})
    string(APPEND content "#include \"${fragment}\"\n")
  endforeach()
  file(GENERATE OUTPUT "${abs_output}" CONTENT "${content}")
  set(${out_var} "${abs_output}" PARENT_SCOPE)
endfunction()
